### ISSUE TITLE
Key Bind for Manually Stopping Process

### ISSUE THREAD

**Issue by fatmagic** [SanjoSolutions/CommodityBuyerAndSeller#1]
Hey Sanjo - love the addon. Would it be possible to add a keybind for manually stopping the process? Right now I close the AH window, wait a few seconds, and then I see it auto-stops. Thanks!

**Comment by SanjoSolutions** [comment]
I have added it with [2.1.0](https://github.com/SanjoSolutions/CommodityBuyerAndSeller/releases/tag/v2.1.0). ;-)

**Comment by fatmagic** [comment]
Awesome! Thank you!
