### ISSUE TITLE
doConfigured() Command not firing in 2.1.1

### ISSUE THREAD

**Issue by fatmagic** [SanjoSolutions/CommodityBuyerAndSeller#3]
Hey Sanjo - adding on to the previous issue from steenert, as I'm not sure it's fixed. 

Running /run CommodityBuyerAndSellerData.doConfigured() is not firing it up. Here is my CommodityBuyerAndSellerData.lua - which was working on 2.0.0:

```
CommodityBuyerAndSellerData = {}

function CommodityBuyerAndSellerData.doConfigured()
	CommodityBuyerAndSeller.sell(193243, 1000, 30, 200)
	CommodityBuyerAndSeller.sell(193244, 1000, 30, 550)
endaq
```

Prices on AH are above the minimums for both items. Just doesn't do anything when I fire off the /run command.
Also double checked the ID's on WoW Head - both are correct for the items in my bag.

_Originally posted by @fatmagic in https://github.com/SanjoSolutions/CommodityBuyerAndSeller/issues/2#issuecomment-1414556822_

**Comment by SanjoSolutions** [comment]
In the last line of the code snippet there seems to be an "aq" after the "end". Maybe it helps to remove that. On my side selling seems to work in 2.1.1.

**Comment by fatmagic** [comment]
Oops.... I probably entered that while thinking I was focused on my notepad. Sorry about that. WIll try now.

**Comment by fatmagic** [comment]
That was it... closing issue! Thank for pointing out the obvious!
