### ISSUE TITLE
Addon no longer working in patch 10.0.7

### ISSUE THREAD

**Issue by steenert** [SanjoSolutions/CommodityBuyerAndSeller#5]
Hi,

Addon has unfortunately stopped working in patch 10.0.7. The following LUA error is received:

`32x [string "CommodityBuyerAndSellerData.doConfigured()"]:1: attempt to index global 'CommodityBuyerAndSellerData' (a nil value)`

**Comment by fatmagic** [comment]
Hey Steenert - it is still working for me. But I'm only using it to sell currently. Are you trying to Buy or Cancel with it? _(I don't know how to fix it, I'm just trying to help narrow down your problem!)_

**Comment by steenert** [comment]
Looks like I had a typo in my **CommodityBuyerAndSellerData.lua** file. It is working fine now, sorry!
